-- MySQL Script generated by MySQL Workbench
-- vie 02 jul 2021 15:53:47 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`PROVEIDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`PROVEIDOR` (
  `id_proveidor` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `porta` VARCHAR(4) NULL,
  `ciutat` VARCHAR(20) NOT NULL,
  `codi_postal` VARCHAR(15) NOT NULL,
  `pais` VARCHAR(20) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(15) NULL,
  `nif` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_proveidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`MARCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`MARCA` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nom_marca` VARCHAR(20) NOT NULL,
  `id_proveidor` INT NOT NULL,
  PRIMARY KEY (`id_marca`),
  INDEX `fk_MARCA_PROVEIDOR_idx` (`id_proveidor` ASC) VISIBLE,
  CONSTRAINT `fk_MARCA_PROVEIDOR`
    FOREIGN KEY (`id_proveidor`)
    REFERENCES `optica`.`PROVEIDOR` (`id_proveidor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`TIPUS_MONTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`TIPUS_MONTURA` (
  `id_tipus_montura` INT NOT NULL AUTO_INCREMENT,
  `descripcio_montura` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_tipus_montura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`CLIENT` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `codi_postal` VARCHAR(15) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_registre` DATE NOT NULL,
  `id_client_recomanat` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  INDEX `fk_CLIENTS_CLIENTS1_idx` (`id_client_recomanat` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTS_CLIENTS1`
    FOREIGN KEY (`id_client_recomanat`)
    REFERENCES `optica`.`CLIENT` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`EMPLEAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`EMPLEAT` (
  `id_empleat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_empleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`ULLERES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`ULLERES` (
  `id_ulleres` INT NOT NULL AUTO_INCREMENT,
  `graduacio_ull_dret` INT NOT NULL,
  `graduacio_ull_esquerra` INT NOT NULL,
  `color_montura` VARCHAR(15) NOT NULL,
  `color_vidre` VARCHAR(15) NOT NULL,
  `preu` INT NOT NULL,
  `id_marca` INT NOT NULL,
  `id_tipus_montura` INT NOT NULL,
  `id_client` INT NOT NULL,
  `id_empleat` INT NOT NULL,
  PRIMARY KEY (`id_ulleres`),
  INDEX `fk_ULLERES_MARCA1_idx` (`id_marca` ASC) VISIBLE,
  INDEX `fk_ULLERES_TIPUS_MONTURA1_idx` (`id_tipus_montura` ASC) VISIBLE,
  INDEX `fk_ULLERES_CLIENTS1_idx` (`id_client` ASC) VISIBLE,
  INDEX `fk_ULLERES_EMPLEAT1_idx` (`id_empleat` ASC) VISIBLE,
  CONSTRAINT `fk_ULLERES_MARCA1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `optica`.`MARCA` (`id_marca`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ULLERES_TIPUS_MONTURA1`
    FOREIGN KEY (`id_tipus_montura`)
    REFERENCES `optica`.`TIPUS_MONTURA` (`id_tipus_montura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ULLERES_CLIENTS1`
    FOREIGN KEY (`id_client`)
    REFERENCES `optica`.`CLIENT` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ULLERES_EMPLEAT1`
    FOREIGN KEY (`id_empleat`)
    REFERENCES `optica`.`EMPLEAT` (`id_empleat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
