-- MySQL Script generated by MySQL Workbench
-- vie 02 jul 2021 17:25:42 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`PROVINCIA` (
  `id_provincia` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`LOCALITAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`LOCALITAT` (
  `id_localitat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `id_provincia` INT NOT NULL,
  PRIMARY KEY (`id_localitat`),
  INDEX `fk_LOCALITAT_PROVINCIA1_idx` (`id_provincia` ASC) VISIBLE,
  CONSTRAINT `fk_LOCALITAT_PROVINCIA1`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria`.`PROVINCIA` (`id_provincia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`CLIENT` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `primer_cognom` VARCHAR(20) NOT NULL,
  `segon_cognom` VARCHAR(20) NULL,
  `adreça` VARCHAR(45) NOT NULL,
  `codi_postal` VARCHAR(15) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `id_provincia` INT NOT NULL,
  `id_localitat` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  INDEX `fk_CLIENT_PROVINCIA_idx` (`id_provincia` ASC) VISIBLE,
  INDEX `fk_CLIENT_LOCALITAT1_idx` (`id_localitat` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENT_PROVINCIA`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria`.`PROVINCIA` (`id_provincia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CLIENT_LOCALITAT1`
    FOREIGN KEY (`id_localitat`)
    REFERENCES `pizzeria`.`LOCALITAT` (`id_localitat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`TIPUS_PRODUCTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`TIPUS_PRODUCTE` (
  `id_tipus` INT NOT NULL,
  `descripcio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`CATEGORIA_PIZZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`CATEGORIA_PIZZA` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`PRODUCTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`PRODUCTE` (
  `id_producte` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  `descripcio` VARCHAR(30) NULL,
  `imatge` BLOB NULL,
  `preu` INT NOT NULL,
  `id_tipus` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producte`),
  INDEX `fk_PRODUCTE_TIPUS_PRODUCTE1_idx` (`id_tipus` ASC) VISIBLE,
  INDEX `fk_PRODUCTE_CATEGORIA_PIZZA1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTE_TIPUS_PRODUCTE1`
    FOREIGN KEY (`id_tipus`)
    REFERENCES `pizzeria`.`TIPUS_PRODUCTE` (`id_tipus`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PRODUCTE_CATEGORIA_PIZZA1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `pizzeria`.`CATEGORIA_PIZZA` (`id_categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`TIPUS_EMPLEAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`TIPUS_EMPLEAT` (
  `id_tipus` INT NOT NULL AUTO_INCREMENT,
  `descripcio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`BOTIGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`BOTIGA` (
  `id_botiga` INT NOT NULL AUTO_INCREMENT,
  `adreça` VARCHAR(45) NOT NULL,
  `codi_postal` VARCHAR(15) NOT NULL,
  `id_provincia` INT NOT NULL,
  `id_localitat` INT NOT NULL,
  PRIMARY KEY (`id_botiga`),
  INDEX `fk_BOTIGA_PROVINCIA1_idx` (`id_provincia` ASC) VISIBLE,
  INDEX `fk_BOTIGA_LOCALITAT1_idx` (`id_localitat` ASC) VISIBLE,
  CONSTRAINT `fk_BOTIGA_PROVINCIA1`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria`.`PROVINCIA` (`id_provincia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_BOTIGA_LOCALITAT1`
    FOREIGN KEY (`id_localitat`)
    REFERENCES `pizzeria`.`LOCALITAT` (`id_localitat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`EMPLEAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`EMPLEAT` (
  `id_empleat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `primer_cognom` VARCHAR(20) NOT NULL,
  `segon_cognom` VARCHAR(20) NULL,
  `nif` VARCHAR(15) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `id_tipus` INT NOT NULL,
  `id_botiga` INT NOT NULL,
  PRIMARY KEY (`id_empleat`),
  INDEX `fk_EMPLEAT_TIPUS_EMPLEAT1_idx` (`id_tipus` ASC) VISIBLE,
  INDEX `fk_EMPLEAT_BOTIGA1_idx` (`id_botiga` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEAT_TIPUS_EMPLEAT1`
    FOREIGN KEY (`id_tipus`)
    REFERENCES `pizzeria`.`TIPUS_EMPLEAT` (`id_tipus`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EMPLEAT_BOTIGA1`
    FOREIGN KEY (`id_botiga`)
    REFERENCES `pizzeria`.`BOTIGA` (`id_botiga`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`COMANDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`COMANDA` (
  `id_comanda` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `tipus_comanda` VARCHAR(15) NOT NULL,
  `quantitat_productes` INT NOT NULL,
  `preu_total` INT NOT NULL,
  `id_client` INT NOT NULL,
  `data_entrega` DATETIME NOT NULL,
  `id_empleat` INT NULL,
  PRIMARY KEY (`id_comanda`),
  INDEX `fk_COMANDA_CLIENT1_idx` (`id_client` ASC) VISIBLE,
  INDEX `fk_COMANDA_EMPLEAT1_idx` (`id_empleat` ASC) VISIBLE,
  CONSTRAINT `fk_COMANDA_CLIENT1`
    FOREIGN KEY (`id_client`)
    REFERENCES `pizzeria`.`CLIENT` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_COMANDA_EMPLEAT1`
    FOREIGN KEY (`id_empleat`)
    REFERENCES `pizzeria`.`EMPLEAT` (`id_empleat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`DETALL_COMANDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`DETALL_COMANDA` (
  `id_comanda` INT NOT NULL,
  `id_producte` INT NOT NULL,
  PRIMARY KEY (`id_comanda`, `id_producte`),
  INDEX `fk_COMANDA_has_PRODUCTE_PRODUCTE1_idx` (`id_producte` ASC) VISIBLE,
  INDEX `fk_COMANDA_has_PRODUCTE_COMANDA1_idx` (`id_comanda` ASC) VISIBLE,
  CONSTRAINT `fk_COMANDA_has_PRODUCTE_COMANDA1`
    FOREIGN KEY (`id_comanda`)
    REFERENCES `pizzeria`.`COMANDA` (`id_comanda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_COMANDA_has_PRODUCTE_PRODUCTE1`
    FOREIGN KEY (`id_producte`)
    REFERENCES `pizzeria`.`PRODUCTE` (`id_producte`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
